version: '3.8'

services:
  api:
    build: ./api
    ports:
      - 6901:6901
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./api/.env

volumes:
  db:
    driver: local
