version: '3.8'

services:
  frontend:
    build: ./web
    ports:
      - 5173:3000
  api:
    build: ./api
    ports:
      - 3001:3001
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./api/.env

volumes:
  db:
    driver: local
